### ISSUE TITLE
python 3.8.2 and vapoursynth R49

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_mingw_libs#6]
Reference https://github.com/DeadSix27/vapoursynth_mingw_libs/issues/10 and 
https://github.com/DeadSix27/python_cross_compile_script/issues/110

**Comment by DeadSix27** [comment]
https://github.com/DeadSix27/vapoursynth_mingw_libs/commit/d90dcf823e4dd8ed034cae80e78234b128a8ffa1
