### ISSUE TITLE
how to build mpv with python?

### ISSUE THREAD

**Issue by zhongfly** [DeadSix27/python_mingw_libs#7]
I'm sorry to bother you with questions that aren't really relevant to this project.
I see your comment that you've successfully compiled mpv with python embedded.So I find this project and want to migrate it to cmake.
I try to build 64bit mpv with python3.11.4.
https://github.com/zhongfly/mpv-winbuild-cmake/tree/python

But there are some problems with mpv compilation,like this:
```
.../install/lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc6DxQEI.ltrans27.ltrans.o:<artificial>:(.text+0x3): undefined reference to `__imp__Py_NotImplementedStruct'

.../install/lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc6DxQEI.ltrans27.ltrans.o:<artificial>:(.text+0x13): undefined reference to `__imp__Py_TrueStruct'

.../install/lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc6DxQEI.ltrans27.ltrans.o:<artificial>:(.text+0x242): undefined reference to `__imp__Py_Dealloc'
```
Can you give me some advice?

**Comment by DeadSix27** [comment]
Look into my script for reference: https://github.com/DeadSix27/py-cross/blob/master/packages/mpv.py and https://github.com/DeadSix27/py-cross/blob/master/packages/python.py
~~I havent pushed latest local changes , but still should be enough to figure it out~~ Updated everything now.

**Comment by zhongfly** [comment]
Fix by change `gendef - $1.dll | sed -r -e 's|^_||' -e 's|@[1-9]+$||' > $1.def` to `gendef - $1.dll` in my code.
